"""empty message

Revision ID: 95028b2fcbc5
Revises: 
Create Date: 2021-01-23 17:45:56.760978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95028b2fcbc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sneakers', sa.Column('inspiration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sneakers', 'inspiration')
    # ### end Alembic commands ###
